from pers import masters

rooms = ["AgACAgEAAxkBAAIBDmSjlDlUwFt87oCdcwGg-6iHHMyaAAJ8qzEbxeQgReWrtORWL0WRAQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBEGSjlEGKkbbg18MdUDPwl67j6r-4AAJ9qzEbxeQgRcH9TDvTNwmKAQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBEmSjlEfQsLyl9iITu-s2TnH7QjJDAAJ-qzEbxeQgRUUJxqvH8eqaAQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBFGSjlE4DnJ9ktUBluhrhHQ0vBiC2AAJ_qzEbxeQgRZL1bTseBRbRAQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBFmSjlFNKREF-FT-hVG4hjIXSHeZEAAKAqzEbxeQgRXMrL0Dj3k16AQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBGGSjlFlBLz4o50Klp58p6ltVsKFuAAKBqzEbxeQgReumvWOUPe02AQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBGmSjlFtPZ0DgrMLIamW9jNgVtA0iAAKCqzEbxeQgRV7ea-FrKi6dAQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBHGSjlGJbCc1mXIv_AZKTw1Lh8adXAAKDqzEbxeQgRWrOL3_YAlt0AQADAgADcwADLwQ",
         "AgACAgEAAxkBAAIBHmSjlGfacJHF50llVkCuHqDLpQmJAAKEqzEbxeQgRS_B2TGnYxNiAQADAgADcwADLwQ"]

hookah = "AgACAgEAAxkBAAIBIGSjlgACgJq5MXF_YPpEWkuCaVLtAAKFqzEbxeQgRdQ2cOO-3lA5AQADAgADcwADLwQ"

actions = ["AgACAgEAAxkBAAIBymSjomb1Z-aZIeJBE53qMkwRtpJWAAKQqzEbxeQgRVwwHhM939RpAQADAgADcwADLwQ"]

menu = {
    "zakus": "AgACAgEAAxkBAAIBImSjlmRwX2vEG1gg1WCqEnPT18QwAAKGqzEbxeQgRWCnI-11gndiAQADAgADcwADLwQ",
    "pizza": "AgACAgEAAxkBAAIBJGSjlrZkxf7WxhIqAZexxoGNZxKrAAKHqzEbxeQgRdTriclY3xboAQADAgADcwADLwQ",
    "drink": "AgACAgEAAxkBAAIBJmSjlwABqomlmf7xHhAC-my1cJFYOQACiKsxG8XkIEUVEtgDB7VYpwEAAwIAA3MAAy8E",
    "krbeer": "AgACAgEAAxkBAAIBKGSjl0Re4ZpWDF9A0DjiT_3sk0tnAAKJqzEbxeQgRRu9lbKnMIF2AQADAgADcwADLwQ",
    "beer": "AgACAgEAAxkBAAIBKmSjl4P2HKpSnIp22G3h458rQAUpAAKKqzEbxeQgRfn6iEMBnrY5AQADAgADcwADLwQ",
    "tea": "AgACAgEAAxkBAAIBLGSjl7c__ntQuMVEArZ9xuvak5nMAAKLqzEbxeQgRQvXsjwzm5OLAQADAgADcwADLwQ",
    "des": "AgACAgEAAxkBAAIBL2SjmX6jydAbJljrHRW87cMYaXUvAAKMqzEbxeQgRaPKxBEPldI1AQADAgADcwADLwQ",
    "snack": "AgACAgEAAxkBAAIBMWSjmbc24IUh6vP6pNEedwSOeHRVAAKNqzEbxeQgRUJA5Qy6w1XWAQADAgADcwADLwQ",
    "menu": "AgACAgEAAxkBAAIBV2SjngM510BvTXV9fWvUM8z2fWl-AAKPqzEbxeQgRUTpWcXZuE0yAQADAgADcwADLwQ"}


logo = "AgACAgEAAxkBAAIBM2SjmqFSmB3E7ej4DLwDC90q2kBNAAKOqzEbxeQgRVQ9O4Utr8PcAQADAgADcwADLwQ"


rent = "AgACAgEAAxkBAAIDi2Srs119sKBNT-equtHxv3wwsN-1AAI0qzEbgfRhRZ1Xy_Hgr9avAQADAgADcwADLwQ"


masters_photo = [i[1] for i in masters.values()]
